kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring  # 指定namespace为monitoring
spec:
  storageClassName: nfs-storage # 指定StorageClass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
